---
title: "Join the lab"
description: |

output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
---

* We are friendly, kind, collaborative, personalized, accommodative, inclusive, supportive and dedicated to both scientific and individual progress. And fun. All are actively welcome, and especially anyone who may not have felt welcome in the past. We value diversity.

* If interested, please send your CV and transcript to this [address](mailto: m2b3.lab@mcgill.ca), along with a brief note outlining why you are interested in the lab.

### Undergraduates

* McGill undergraduates are welcome as mentored independent research students, or via research courses like PHGY 396, COGS 444 D1/D2, PSYC 395/494, COMP 401, etc. There are programming-based data-analysis/theoretical projects for those with programming skills and human psychophysics-based projects for those with an interest in that. There are also projects related to music. Please send your CV and transcript to this [e-mail](mailto: m2b3.lab@mcgill.ca). 

* There are several possible fellowships for international undergrads from under-represented countries, including [here](https://www.educanada.ca/scholarships-bourses/can/institutions/asean-anase.aspx?lang=eng), [here](https://www.educanada.ca/scholarships-bourses/can/institutions/study-in-canada-sep-etudes-au-canada-pct.aspx?lang=eng), and [here](https://www.educanada.ca/scholarships-bourses/can/institutions/elap-pfla.aspx?lang=eng). 

### Masters and PhD

* Graduate students (Masters and PhD) can apply via either the Physiology graduate program or the IPN program - the preferred option depends on each individual circumstance. For some applicants, the QLS program may also be a good option. McGill allows applicants to apply for two programs with one application fee.  We are particularly interested in those who feel comfortable thinking quantitatively; however, this is not a necessary criterion and depending on the projects available, slots for those with other skills may also be available.

* There are several fellowships available for graduate student applicants from specific countries. Specific examples, taken from [this source](https://www.mcgill.ca/gps/funding/international-student-postdoctoral-funding-opportunities/international), are Greece, China,  Mexico, UAE, Ghana, Tunisia, Egypt, Chile and differential fee waivers for students from India, Brazil etc. (these lists are not complete). French students have a full differential fee waiver. There are possibilities for students from even more countries listed [here](https://www.mcgill.ca/gps/funding/international-student-postdoctoral-funding-opportunities/opportunities-available-through-international-agencies).

* Students from the McGill-UESTC IPN-China program are welcome. The lab is actively engaged with this program.

### Postdocs and research associates

* Postdoc openings depend on the lab's funding situation, the eligibility for external postdoc grants, etc. There are a variety of options that change year-by-year. Enquiries are welcome as is sponsorship for international fellowships like [HFSP](https://www.hfsp.org/funding/hfsp-funding/postdoctoral-fellowships) etc.